# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jeremiah/src/Carp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jeremiah/src/Carp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeremiah/src/Carp/CMakeFiles /home/jeremiah/src/Carp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeremiah/src/Carp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named carp-repl

# Build rule for target.
carp-repl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 carp-repl
.PHONY : carp-repl

# fast build rule for target.
carp-repl/fast:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/build
.PHONY : carp-repl/fast

src/bytecode.o: src/bytecode.c.o

.PHONY : src/bytecode.o

# target to build an object file
src/bytecode.c.o:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/bytecode.c.o
.PHONY : src/bytecode.c.o

src/bytecode.i: src/bytecode.c.i

.PHONY : src/bytecode.i

# target to preprocess a source file
src/bytecode.c.i:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/bytecode.c.i
.PHONY : src/bytecode.c.i

src/bytecode.s: src/bytecode.c.s

.PHONY : src/bytecode.s

# target to generate assembly for a file
src/bytecode.c.s:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/bytecode.c.s
.PHONY : src/bytecode.c.s

src/call_ffi.o: src/call_ffi.c.o

.PHONY : src/call_ffi.o

# target to build an object file
src/call_ffi.c.o:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/call_ffi.c.o
.PHONY : src/call_ffi.c.o

src/call_ffi.i: src/call_ffi.c.i

.PHONY : src/call_ffi.i

# target to preprocess a source file
src/call_ffi.c.i:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/call_ffi.c.i
.PHONY : src/call_ffi.c.i

src/call_ffi.s: src/call_ffi.c.s

.PHONY : src/call_ffi.s

# target to generate assembly for a file
src/call_ffi.c.s:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/call_ffi.c.s
.PHONY : src/call_ffi.c.s

src/env.o: src/env.c.o

.PHONY : src/env.o

# target to build an object file
src/env.c.o:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/env.c.o
.PHONY : src/env.c.o

src/env.i: src/env.c.i

.PHONY : src/env.i

# target to preprocess a source file
src/env.c.i:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/env.c.i
.PHONY : src/env.c.i

src/env.s: src/env.c.s

.PHONY : src/env.s

# target to generate assembly for a file
src/env.c.s:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/env.c.s
.PHONY : src/env.c.s

src/eval.o: src/eval.c.o

.PHONY : src/eval.o

# target to build an object file
src/eval.c.o:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/eval.c.o
.PHONY : src/eval.c.o

src/eval.i: src/eval.c.i

.PHONY : src/eval.i

# target to preprocess a source file
src/eval.c.i:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/eval.c.i
.PHONY : src/eval.c.i

src/eval.s: src/eval.c.s

.PHONY : src/eval.s

# target to generate assembly for a file
src/eval.c.s:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/eval.c.s
.PHONY : src/eval.c.s

src/gc.o: src/gc.c.o

.PHONY : src/gc.o

# target to build an object file
src/gc.c.o:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/gc.c.o
.PHONY : src/gc.c.o

src/gc.i: src/gc.c.i

.PHONY : src/gc.i

# target to preprocess a source file
src/gc.c.i:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/gc.c.i
.PHONY : src/gc.c.i

src/gc.s: src/gc.c.s

.PHONY : src/gc.s

# target to generate assembly for a file
src/gc.c.s:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/gc.c.s
.PHONY : src/gc.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/main.c.s
.PHONY : src/main.c.s

src/match.o: src/match.c.o

.PHONY : src/match.o

# target to build an object file
src/match.c.o:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/match.c.o
.PHONY : src/match.c.o

src/match.i: src/match.c.i

.PHONY : src/match.i

# target to preprocess a source file
src/match.c.i:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/match.c.i
.PHONY : src/match.c.i

src/match.s: src/match.c.s

.PHONY : src/match.s

# target to generate assembly for a file
src/match.c.s:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/match.c.s
.PHONY : src/match.c.s

src/obj.o: src/obj.c.o

.PHONY : src/obj.o

# target to build an object file
src/obj.c.o:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/obj.c.o
.PHONY : src/obj.c.o

src/obj.i: src/obj.c.i

.PHONY : src/obj.i

# target to preprocess a source file
src/obj.c.i:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/obj.c.i
.PHONY : src/obj.c.i

src/obj.s: src/obj.c.s

.PHONY : src/obj.s

# target to generate assembly for a file
src/obj.c.s:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/obj.c.s
.PHONY : src/obj.c.s

src/obj_array.o: src/obj_array.c.o

.PHONY : src/obj_array.o

# target to build an object file
src/obj_array.c.o:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/obj_array.c.o
.PHONY : src/obj_array.c.o

src/obj_array.i: src/obj_array.c.i

.PHONY : src/obj_array.i

# target to preprocess a source file
src/obj_array.c.i:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/obj_array.c.i
.PHONY : src/obj_array.c.i

src/obj_array.s: src/obj_array.c.s

.PHONY : src/obj_array.s

# target to generate assembly for a file
src/obj_array.c.s:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/obj_array.c.s
.PHONY : src/obj_array.c.s

src/obj_conversions.o: src/obj_conversions.c.o

.PHONY : src/obj_conversions.o

# target to build an object file
src/obj_conversions.c.o:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/obj_conversions.c.o
.PHONY : src/obj_conversions.c.o

src/obj_conversions.i: src/obj_conversions.c.i

.PHONY : src/obj_conversions.i

# target to preprocess a source file
src/obj_conversions.c.i:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/obj_conversions.c.i
.PHONY : src/obj_conversions.c.i

src/obj_conversions.s: src/obj_conversions.c.s

.PHONY : src/obj_conversions.s

# target to generate assembly for a file
src/obj_conversions.c.s:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/obj_conversions.c.s
.PHONY : src/obj_conversions.c.s

src/obj_string.o: src/obj_string.c.o

.PHONY : src/obj_string.o

# target to build an object file
src/obj_string.c.o:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/obj_string.c.o
.PHONY : src/obj_string.c.o

src/obj_string.i: src/obj_string.c.i

.PHONY : src/obj_string.i

# target to preprocess a source file
src/obj_string.c.i:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/obj_string.c.i
.PHONY : src/obj_string.c.i

src/obj_string.s: src/obj_string.c.s

.PHONY : src/obj_string.s

# target to generate assembly for a file
src/obj_string.c.s:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/obj_string.c.s
.PHONY : src/obj_string.c.s

src/primops.o: src/primops.c.o

.PHONY : src/primops.o

# target to build an object file
src/primops.c.o:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/primops.c.o
.PHONY : src/primops.c.o

src/primops.i: src/primops.c.i

.PHONY : src/primops.i

# target to preprocess a source file
src/primops.c.i:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/primops.c.i
.PHONY : src/primops.c.i

src/primops.s: src/primops.c.s

.PHONY : src/primops.s

# target to generate assembly for a file
src/primops.c.s:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/primops.c.s
.PHONY : src/primops.c.s

src/process.o: src/process.c.o

.PHONY : src/process.o

# target to build an object file
src/process.c.o:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/process.c.o
.PHONY : src/process.c.o

src/process.i: src/process.c.i

.PHONY : src/process.i

# target to preprocess a source file
src/process.c.i:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/process.c.i
.PHONY : src/process.c.i

src/process.s: src/process.c.s

.PHONY : src/process.s

# target to generate assembly for a file
src/process.c.s:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/process.c.s
.PHONY : src/process.c.s

src/reader.o: src/reader.c.o

.PHONY : src/reader.o

# target to build an object file
src/reader.c.o:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/reader.c.o
.PHONY : src/reader.c.o

src/reader.i: src/reader.c.i

.PHONY : src/reader.i

# target to preprocess a source file
src/reader.c.i:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/reader.c.i
.PHONY : src/reader.c.i

src/reader.s: src/reader.c.s

.PHONY : src/reader.s

# target to generate assembly for a file
src/reader.c.s:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/reader.c.s
.PHONY : src/reader.c.s

src/repl.o: src/repl.c.o

.PHONY : src/repl.o

# target to build an object file
src/repl.c.o:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/repl.c.o
.PHONY : src/repl.c.o

src/repl.i: src/repl.c.i

.PHONY : src/repl.i

# target to preprocess a source file
src/repl.c.i:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/repl.c.i
.PHONY : src/repl.c.i

src/repl.s: src/repl.c.s

.PHONY : src/repl.s

# target to generate assembly for a file
src/repl.c.s:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/repl.c.s
.PHONY : src/repl.c.s

src/unify.o: src/unify.c.o

.PHONY : src/unify.o

# target to build an object file
src/unify.c.o:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/unify.c.o
.PHONY : src/unify.c.o

src/unify.i: src/unify.c.i

.PHONY : src/unify.i

# target to preprocess a source file
src/unify.c.i:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/unify.c.i
.PHONY : src/unify.c.i

src/unify.s: src/unify.c.s

.PHONY : src/unify.s

# target to generate assembly for a file
src/unify.c.s:
	$(MAKE) -f CMakeFiles/carp-repl.dir/build.make CMakeFiles/carp-repl.dir/src/unify.c.s
.PHONY : src/unify.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... carp-repl"
	@echo "... src/bytecode.o"
	@echo "... src/bytecode.i"
	@echo "... src/bytecode.s"
	@echo "... src/call_ffi.o"
	@echo "... src/call_ffi.i"
	@echo "... src/call_ffi.s"
	@echo "... src/env.o"
	@echo "... src/env.i"
	@echo "... src/env.s"
	@echo "... src/eval.o"
	@echo "... src/eval.i"
	@echo "... src/eval.s"
	@echo "... src/gc.o"
	@echo "... src/gc.i"
	@echo "... src/gc.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/match.o"
	@echo "... src/match.i"
	@echo "... src/match.s"
	@echo "... src/obj.o"
	@echo "... src/obj.i"
	@echo "... src/obj.s"
	@echo "... src/obj_array.o"
	@echo "... src/obj_array.i"
	@echo "... src/obj_array.s"
	@echo "... src/obj_conversions.o"
	@echo "... src/obj_conversions.i"
	@echo "... src/obj_conversions.s"
	@echo "... src/obj_string.o"
	@echo "... src/obj_string.i"
	@echo "... src/obj_string.s"
	@echo "... src/primops.o"
	@echo "... src/primops.i"
	@echo "... src/primops.s"
	@echo "... src/process.o"
	@echo "... src/process.i"
	@echo "... src/process.s"
	@echo "... src/reader.o"
	@echo "... src/reader.i"
	@echo "... src/reader.s"
	@echo "... src/repl.o"
	@echo "... src/repl.i"
	@echo "... src/repl.s"
	@echo "... src/unify.o"
	@echo "... src/unify.i"
	@echo "... src/unify.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

